# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - pip install -U tox-travis codecov
  - pip install tox-conda

# Command to run tests, e.g. python setup.py test
script:
  - tox -vv

